/*
 * Apex scheduler class that can be used to easily schedule new instances
 * of the batch task creation class.
 * */

public class DateBatchTaskScheduler 
{
/*    public String objectName;
    public DateBatchTaskCreation apexBatch;
    
    public DateBatchTaskScheduler(String objectAPIname) {
      
    }
    
    public void execute(SchedulableContext ctx) 
    {
        if(objectName<>'') {
        	Database.executeBatch(apexBatch);
        }
    } */
}